services:
  app:
    build:
      context: .
    tty: true
    volumes:
      - ./:/app
      - app_node_modules:/app/node_modules  # 匿名ボリュームを使用
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"

volumes:
  app_node_modules:  # 匿名ボリュームの定義